CREATE TABLE DELI (
DELI_ID   NUMERIC(10,0) PRIMARY KEY,
DELI_NAME VARCHAR(20) NOT NULL
);

CREATE TABLE CUSTOMERS (
CUST_ID      NUMERIC(10,0) PRIMARY KEY,
DELI_ID NUMERIC (10,0) REFERENCES DELI,
LOYAL_ID	NUMERIC (10,0) REFERENCES LOYALTY,
CUST_FNAME   VARCHAR(20) NOT NULL,
CUST_LNAME   VARCHAR(20) NOT NULL,
CUST_STREET    VARCHAR(10) NOT NULL,
CUST_CITY    VARCHAR(10) NOT NULL,
CUST_STATE    VARCHAR(10) NOT NULL,
CUST_ZIP    VARCHAR(10) NOT NULL,
CUST_PHONE  NUMERIC(10) NOT NULL,
CUST_EMAIL    VARCHAR(10) NOT NULL
);

CREATE TABLE LOYALTY (
LOYAL_ID NUMERIC(10,0) PRIMARY KEY,
CUST_ID NUMERIC (10,0) REFERENCES LOYALTY,
);

CREATE TABLE VENDOR (
VEND_ID NUMERIC(10,0) PRIMARY KEY,
VEN_1 VARCHAR(120) NOT NULL,
VEN_2 VARCHAR(120) NOT NULL,
VEN_3 VARCHAR(120) NOT NULL,
VEN_4 VARCHAR(120) NOT NULL,
VEN_5 VARCHAR(120) NOT NULL,
VEN_6 VARCHAR(120) NOT NULL,
VEN_7 VARCHAR(120) NOT NULL,
VEN_8 VARCHAR(120) NOT NULL,
VEN_9 VARCHAR(120) NOT NULL,
);

CREATE TABLE MENU (
MENU_ID NUMERIC(10) PRIMARY KEY,
BEV_NAME VARCHAR(120),
SAND_1 VARCHAR(120) NOT NULL,
SAND_2 VARCHAR(120) NOT NULL,
SAND_3 VARCHAR(120) NOT NULL,
SAND_4 VARCHAR(120) NOT NULL,
SAND_5 VARCHAR(120) NOT NULL,
SAND_6 VARCHAR(120) NOT NULL,
SAND_7 VARCHAR(120) NOT NULL,
SAND_8 VARCHAR(120) NOT NULL,
SAND_9 VARCHAR(120) NOT NULL,
SAND_10 VARCHAR(120) NOT NULL,
);

CREATE TABLE STANDARD_SANDWHICH (
STAND_ID NUMERIC(10,0) PRIMARY KEY,
ORDER_ID NUMERIC (10,0) REFERENCES ORDERS,
PROD_ID NUMERIC (10,0) REFERENCES PRODUCE,
MEAT_ID NUMERIC (10,0) REFERENCES MEAT,
COND_ID NUMERIC (10,0) REFERENCES CONDIMENTS,
);

CREATE TABLE CUSTOM_SANDWICH (
CUSTOM_ID NUMERIC(10,0) PRIMARY KEY,
ORDER_ID NUMERIC(10,0) REFERENCES ORDERS,
);

CREATE TABLE PRODUCE (
PROD_ID NUMERIC(10,0) NOT NULL,
MENU_ID NUMERIC(10,0) NOT NULL,
PROD_NAME VARCHAR(120) NOT NULL,
PROD_QTY NUMERIC(10,0) NOT NULL,
PROD_PRICE NUMERIC(10,0) NOT NULL,
PRIMARY KEY (PROD_ID, MENU_ID),
);

CREATE TABLE BEVERAGES (
BEV_ID NUMERIC(10,0) NOT NULL,
MENU_ID NUMERIC(10,0) NOT NULL,
BEV_NAME VARCHAR(120) NOT NULL,
BEV_QTY NUMERIC(10,0) NOT NULL,
BEV_PRICE NUMERIC(10,0) NOT NULL,
PRIMARY KEY (BEV_ID, MENU_ID),
);

CREATE TABLE MEAT (
MEAT_ID NUMERIC(10,0) NOT NULL,
MENU_ID NUMERIC(10,0) NOT NULL,
MEAT_NAME VARCHAR(120) NOT NULL,
MEAT_QTY NUMERIC(10,0) NOT NULL,
MEAT_PRICE NUMERIC(10,0) NOT NULL,
PRIMARY KEY (MEAT_ID, MENU_ID),
);

CREATE TABLE CONDIMENT (
COND_ID NUMERIC(10,0) NOT NULL,
MENU_ID NUMERIC(10,0) NOT NULL,
COND_NAME VARCHAR(120) NOT NULL,
COND_QTY NUMERIC(10,0) NOT NULL,
COND_PRICE NUMERIC(10,0) NOT NULL,
PRIMARY KEY (COND_ID, MENU_ID),
);

CREATE TABLE ORDERS (
ORDER_ID NUMERIC(10,0),
CUST_ID NUMERIC(10,0) NOT NULL,
PROD_ID NUMERIC(10,0) REFERENCES PRODUCE,
MEAT_ID NUMERIC(10,0) REFERENCES MEAT,
BEV_ID NUMERIC (10,0) REFERENCES BEVERAGES,
COND_ID NUMERIC(10,0) REFERENCES CONDIMENTS,
ORDER_TOTAL NUMERIC(20) NOT NULL,
PRIMARY KEY (ORDER_ID, CUST_ID),
);

CREATE TABLE TRANSACTIONS (
TRANS_ID NUMERIC(10,0) NOT NULL,
ORDER_ID NUMERIC (10,0) NOT NULL,
CUST_ID NUMERIC (10,0) NOT NULL,
TRANS_TYPE VARCHAR(10,0) NOT NULL,
TRANS_STATUS VARCHAR(10,0) NOT NULL,
PRIMARY KEY (TRANS_ID, ORDER_ID, CUST_ID),
);


CREATE TABLE RECEIPT (
REC_ID NUMERIC (10,0) PRIMARY KEY,
CUST_ID NUMERIC (10,0) REFERENCES CUSTOMERS,
TRANS_ID NUMERIC(10,0) REFERENCES TRANSACTIONS,
ORDER_ID NUMERIC(10,0) REFERENCES ORDERS,
);