//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliApp
{
    using System;
    using System.Collections.Generic;

    public partial class ACCOUNT
    {
        public int ACC_ID { get; set; }
        public int SAND_ID { get; set; }
        public decimal ACC_REVENUE { get; set; }
        public decimal ACC_COST { get; set; }
        public decimal ACC_PROFIT { get; set; }
        public System.DateTime ACC_DATE { get; set; }
    
        public virtual SANDWICH SANDWICH { get; set; }
    }
}
