//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppContext : DbContext
    {
        public AppContext()
            : base("name=AppContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCOUNT> ACCOUNTS { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERS { get; set; }
        public virtual DbSet<INVENTORY_ITEMS> INVENTORY_ITEMS { get; set; }
        public virtual DbSet<ITEM_CATEGORIES> ITEM_CATEGORIES { get; set; }
        public virtual DbSet<LOYAL_CUSTOMERS> LOYAL_CUSTOMERS { get; set; }
        public virtual DbSet<MENU_OPTIONS> MENU_OPTIONS { get; set; }
        public virtual DbSet<ORDER_LINES> ORDER_LINES { get; set; }
        public virtual DbSet<ORDER> ORDERS { get; set; }
        public virtual DbSet<SANDWICH> SANDWICHES { get; set; }
        public virtual DbSet<VENDOR_ITEMS> VENDOR_ITEMS { get; set; }
        public virtual DbSet<VENDOR> VENDORS { get; set; }
    }
}
