//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTORY_ITEMS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INVENTORY_ITEMS()
        {
            this.VENDOR_ITEMS = new HashSet<VENDOR_ITEMS>();
            this.MENU_OPTIONS = new HashSet<MENU_OPTIONS>();
        }
    
        public int INV_ID { get; set; }
        public int CAT_ID { get; set; }
        public string INV_NAME { get; set; }
        public int INV_QUANTITY { get; set; }
    
        public virtual ITEM_CATEGORIES ITEM_CATEGORIES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENDOR_ITEMS> VENDOR_ITEMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENU_OPTIONS> MENU_OPTIONS { get; set; }
    }
}
