//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANDWICH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANDWICH()
        {
            this.ACCOUNTS = new HashSet<ACCOUNT>();
        }
    
        public int SAND_ID { get; set; }
        public int MENU_ID { get; set; }
        public string SAND_NAME { get; set; }
        public string SAND_MEAT_TYPE { get; set; }
        public int SAND_MEAT_QUANTITY { get; set; }
        public string SAND_CHEESE_TYPE { get; set; }
        public string SAND_BREAD_TYPE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACCOUNT> ACCOUNTS { get; set; }
        public virtual MENU_OPTIONS MENU_OPTIONS { get; set; }
    }
}
